import type { Metadata } from "next";
import { Alfa_Slab_One } from "next/font/google";
import "./globals.css";

import React from "react";

import AuthProvider from "./ReactComponents/AuthProvider"

import Header from "./ReactComponents/Header"
import Footer from "./ReactComponents/Footer"

const alfaSlab = Alfa_Slab_One({
  variable: "--font-alfa",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "ItsDone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${alfaSlab.variable} h-full antialiased`}
    >
      <AuthProvider>
        <body className="min-h-full ">
          <Header />

          {children}

          <Footer />
        </body>
      </AuthProvider>
    </html >
  );
}
