import type { Metadata } from "next";
import { Alfa_Slab_One } from "next/font/google";
import "./globals.css";

import Image from "next/image";
import profilePic from "./src/profilepic.png";
import morePic from "./src/more.png"

import StarsCounter from "./ReactComponents/StarsCounter"
import StreakCounter from "./ReactComponents/StreakCounter"

const alfaSlab = Alfa_Slab_One({
  variable: "--font-alfa",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${alfaSlab.variable} h-full antialiased`}
    >

      <body className="min-h-full">

        <header className="w-[99%] ml-auto mr-auto bg-[#635D5C] text-4xl border-solid border-4 rounded-3xl p-2 mt-1">

          <div className="flex gap-15 flex flex-row items-center">

            <div className="w-14 h-14 rounded-full overflow-hidden border border-gray-200 transition-transform duration-300 hover:scale-110 cursor-pointer hover:border-white">
              <Image src={profilePic} width={70} height={70} alt="ProfilePic" loading="eager" />
            </div>

            <StarsCounter starsCount={50} />
            <StreakCounter streakCount={50} />

            <p className="font-logo text-5xl ml-[20%]">ItsDone✔️</p>

            <div className="border-solid border-4 p-1 rounded-3xl ml-auto transition-all duration-300 hover:scale-110 hover:bg-white/10 cursor-pointer">
              <Image src={morePic} width={50} height={50} alt="More" loading="eager" />
            </div>

          </div>
        </header>
        {children}
      </body>
    </html >
  );
}
